name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        type: string
      aws-region:
        type: string

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: grocery_prices.zip
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Assume AWS role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        id: init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        id: apply
        working-directory: infra
        run: terraform apply -auto-approve
