name: Generate Image Tag

on:
  workflow_call:
    inputs:
      aws-region:
        type: string

    outputs:
      image-tag:
        value: ${{ jobs.generate-tag.outputs.image-tag }}

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    outputs:
      image-tag: ${{ steps.generate-tag.outputs.IMAGE_DESTINATION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assume AWS role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ inputs.aws-region }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Generate image tag
        id: generate-tag
        env:
          REPOSITORY: grocery-prices
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REGISTRY_ALIAS: e2q6m3r8
        run: |
          IMAGE_TAG=$(bash infra/scripts/generate_version.sh)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo $IMAGE_TAG
          echo "IMAGE_DESTINATION=${{ env.REGISTRY }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
