name: "Grocery Prices Lambda Workflow"

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '*/**.py'
      - '!tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - '*/**.py'


jobs:
  build-and-test-lambda:
    uses: ./.github/workflows/build-and-test-lambda.yaml

  sonarqube:
    uses: ./.github/workflows/sonarqube.yaml
    secrets: inherit

  terraform-plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    needs: [build-and-test-lambda]
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      environment: production
      aws-region: us-east-1
    secrets: inherit

  prod-approval:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    environment: prod-approval
    steps:
     - run: echo "Production approval."

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: [prod-approval]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
      aws-region: us-east-1
    secrets: inherit
