name: SonarQube Workflow

on:
  workflow_call:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download UI test coverage
        uses: actions/download-artifact@v4
        with:
          name: jest-coverage
          path: ./coverage

      - uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_API_TOKEN }}
