name: UI Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - '!ui/**/*.test.ts'
      - '!ui/**/*.test.tsx'
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'

jobs:
  build-and-test-ui:
    uses: ./.github/workflows/build-and-test-ui.yaml

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download UI test coverage
        uses: actions/download-artifact@v4
        with:
          name: jest-coverage
          path: ./coverage

      - uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_API_TOKEN }}
